In [71]:
import pandas as pd
import psycopg2

In [72]:
def create_database():
    # connect to default database  
    conn = psycopg2.connect("dbname=postgres user=postgres password=me821989ME@")
    cur = conn.cursor()
    conn.set_session(autocommit=True)

    # create sparkify database with UTF8 encoding
    cur.execute("DROP DATABASE IF EXISTS covid WITH (FORCE)")
    cur.execute("CREATE DATABASE covid")

    # close connection to default database
    conn.close()

    # connect to sparkify database
    conn = psycopg2.connect("dbname=covid user=postgres password=me821989ME@")
    cur = conn.cursor()
    
    return cur, conn

##### Load data and view 5 raws

In [73]:
covid_confirmed = pd.read_csv("D:\Data_Engineering\COVID-19 Localized Scenario Planner\covid_confirmed_usafacts.csv")
covid_confirmed.head()

,countyFIPS,County Name,State,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,4/10/20,4/11/20,4/12/20,4/13/20,4/14/20
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,12,12,12,12,17,17,19,19,19,19
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,34,38,42,49,59,59,66,71,78,78
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,2,3,3,3,7,9,10,10,9,9
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,7,7,8,9,11,11,13,16,17,17

In [74]:
covid_confirmed.columns

Index(['countyFIPS', 'County Name', 'State', 'stateFIPS', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20', '1/28/20', '1/29/20',
       '1/30/20', '1/31/20', '2/1/20', '2/2/20', '2/3/20', '2/4/20', '2/5/20',
       '2/6/20', '2/7/20', '2/8/20', '2/9/20', '2/10/20', '2/11/20', '2/12/20',
       '2/13/20', '2/14/20', '2/15/20', '2/16/20', '2/17/20', '2/18/20',
       '2/19/20', '2/20/20', '2/21/20', '2/22/20', '2/23/20', '2/24/20',
       '2/25/20', '2/26/20', '2/27/20', '2/28/20', '2/29/20', '3/1/20',
       '3/2/20', '3/3/20', '3/4/20', '3/5/20', '3/6/20', '3/7/20', '3/8/20',
       '3/9/20', '3/10/20', '3/11/20', '3/12/20', '3/13/20', '3/14/20',
       '3/15/20', '3/16/20', '3/17/20', '3/18/20', '3/19/20', '3/20/20',
       '3/21/20', '3/22/20', '3/23/20', '3/24/20', '3/25/20', '3/26/20',
       '3/27/20', '3/28/20', '3/29/20', '3/30/20', '3/31/20', '4/1/20',
       '4/2/20', '4/3/20', '4/4/20', '4/5/20', '4/6/20', '4/7/20', '4/8/20',
       '4/9/20', '4/10/20', '4/11/20', '4/12/20', '4/13/20', '4/14/20'],
      dtype='object')

In [75]:
covid_confirmed_april = covid_confirmed[['countyFIPS', 'County Name', 'State', 'stateFIPS', '4/1/20',
       '4/2/20', '4/3/20', '4/4/20', '4/5/20', '4/6/20', '4/7/20', '4/8/20',
       '4/9/20', '4/10/20', '4/11/20', '4/12/20', '4/13/20', '4/14/20']]
covid_confirmed_april.head()

,countyFIPS,County Name,State,stateFIPS,4/1/20,4/2/20,4/3/20,4/4/20,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,4/10/20,4/11/20,4/12/20,4/13/20,4/14/20
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,10,10,12,12,12,12,12,12,17,17,19,19,19,19
2,1003,Baldwin County,AL,1,23,25,28,29,34,38,42,49,59,59,66,71,78,78
3,1005,Barbour County,AL,1,0,0,1,2,2,3,3,3,7,9,10,10,9,9
4,1007,Bibb County,AL,1,3,4,4,4,7,7,8,9,11,11,13,16,17,17

In [76]:
covid_country_population = pd.read_csv("D:\Data_Engineering\COVID-19 Localized Scenario Planner\covid_county_population_usafacts.csv")
covid_country_population.head()

   countyFIPS            County Name State  population
0           0  Statewide Unallocated    AL           0
1        1001         Autauga County    AL       55869
2        1003         Baldwin County    AL      223234
3        1005         Barbour County    AL       24686
4        1007            Bibb County    AL       22394

In [77]:
covid_deaths = pd.read_csv("D:\Data_Engineering\COVID-19 Localized Scenario Planner\covid_deaths_usafacts.csv")
covid_deaths.head()

,countyFIPS,County Name,State,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,4/10/20,4/11/20,4/12/20,4/13/20,4/14/20
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,0,0,0,1,1,1,1,1,1,1
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [78]:
covid_deaths_april = covid_deaths[['countyFIPS', 'County Name', 'State', 'stateFIPS', '4/1/20',
       '4/2/20', '4/3/20', '4/4/20', '4/5/20', '4/6/20', '4/7/20', '4/8/20',
       '4/9/20', '4/10/20', '4/11/20', '4/12/20', '4/13/20', '4/14/20']]
covid_deaths_april.head()

,countyFIPS,County Name,State,stateFIPS,4/1/20,4/2/20,4/3/20,4/4/20,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,4/10/20,4/11/20,4/12/20,4/13/20,4/14/20
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,0,1,1,1,1,1,1,1
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1005,Barbour County,AL,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1007,Bibb County,AL,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [79]:
cur, conn = create_database()

In [80]:
covid_country_population_table_create = ("""CREATE TABLE IF NOT EXISTS covid_country_population (
    countyFIPS NUMERIC,
    County_Name VARCHAR,
    State VARCHAR,
    population NUMERIC
)""")

cur.execute(covid_country_population_table_create)
conn.commit()

In [81]:
covid_confirmed_april_table_create = ("""CREATE TABLE IF NOT EXISTS covid_confirmed_april(
    countyFIPS NUMERIC,
    County_Name VARCHAR,
    State VARCHAR,
    stateFIPS NUMERIC,
    D4_1_20 NUMERIC,
    D4_2_20 NUMERIC,
    D4_3_20 NUMERIC,
    D4_4_20 NUMERIC,
    D4_5_20 NUMERIC,
    D4_6_20 NUMERIC,
    D4_7_20 NUMERIC,
    D4_8_20 NUMERIC,
    D4_9_20 NUMERIC,
    D4_10_20 NUMERIC,
    D4_11_20 NUMERIC,
    D4_12_20 NUMERIC,
    D4_13_20 NUMERIC,
    D4_14_20 NUMERIC
)""")

cur.execute(covid_confirmed_april_table_create)
conn.commit()

In [82]:
covid_deaths_april_table_create = ("""CREATE TABLE IF NOT EXISTS covid_deaths_april(
    countyFIPS NUMERIC,
    County_Name VARCHAR,
    State VARCHAR,
    stateFIPS NUMERIC,
    D4_1_20 NUMERIC,
    D4_2_20 NUMERIC,
    D4_3_20 NUMERIC,
    D4_4_20 NUMERIC,
    D4_5_20 NUMERIC,
    D4_6_20 NUMERIC,
    D4_7_20 NUMERIC,
    D4_8_20 NUMERIC,
    D4_9_20 NUMERIC,
    D4_10_20 NUMERIC,
    D4_11_20 NUMERIC,
    D4_12_20 NUMERIC,
    D4_13_20 NUMERIC,
    D4_14_20 NUMERIC
)""")

cur.execute(covid_deaths_april_table_create)
conn.commit()

In [83]:
covid_country_population_table_insert = ("""INSERT INTO covid_country_population (
    countyFIPS, County_Name, State, population) values (%s, %s, %s, %s)
""")

In [84]:
for i, row in covid_country_population.iterrows():
    cur.execute(covid_country_population_table_insert, list(row))
    conn.commit()

In [85]:
covid_confirmed_april_table_insert = ("""INSERT INTO covid_confirmed_april(
    countyFIPS, County_Name, State, stateFIPS, D4_1_20, D4_2_20, D4_3_20, D4_4_20, D4_5_20, D4_6_20, D4_7_20, D4_8_20, D4_9_20, D4_10_20, D4_11_20, D4_12_20, D4_13_20, D4_14_20) \
        values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """)

In [86]:
for i, row in covid_confirmed_april.iterrows():
    cur.execute(covid_confirmed_april_table_insert, list(row))
    conn.commit()

In [87]:
covid_deaths_april_table_insert = ("""INSERT INTO covid_deaths_april(
    countyFIPS, County_Name, State, stateFIPS, D4_1_20, D4_2_20, D4_3_20, D4_4_20, D4_5_20, D4_6_20, D4_7_20, D4_8_20, D4_9_20, D4_10_20, D4_11_20, D4_12_20, D4_13_20, D4_14_20) \
        values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """)

In [88]:
for i, row in covid_deaths_april.iterrows():
    cur.execute(covid_deaths_april_table_insert, list(row))
    conn.commit()